# confused from some unknown errors!
- hosts: ubuntu1604
  connection: local
  remote_user: abe
  gather_facts: no
  vars:
    home_dir: /home/abe
    host_home_dir: /Users/abe
    install_user: abe
    install_group: abe

    ruby_version: 2.4.0
    node_version: 6.9.4
    erlang_version: 19.2
    elixir_version: 1.4.0
    # python2_version: 2.7.12
    # python3_version: 3.5.2
    golang_version: 1.7.4
    php_version: 7.1.0

    shell: bash

  tasks:
    - include: roles/install_core_packages_ubuntu.yml
      become: yes
      become_user: root
    - include: roles/docker.yml
      become: yes
      become_user: root
    - include: roles/private.yml

    - include: roles/anyenv.yml
    - include: roles/ruby.yml
    - include: roles/node.yml
    - include: roles/erlang.yml
    - include: roles/elixir.yml
    # - include: roles/python.yml
    # - include: roles/go.yml
    - include: roles/php.yml
    - include: roles/haskell.yml
      become: yes
      become_user: root

