- hosts: localhost
  connection: local
  remote_user: abe
  gather_facts: yes
  vars:
    home_dir: /home/abe
    install_user: abe
    install_group: abe

    ruby_version: 2.4.1
    node_version: 6.10.3
    erlang_version: 19.3
    elixir_version: 1.4.2
    # golang_version: 1.8.1
    php_version: 7.1.3
    swift_version: 3.0.2

    shell: bash

  tasks:
    - include: roles/install_core_packages_ubuntu.yml
      become: yes
      become_user: root
    - include: roles/docker.yml
      become: yes
      become_user: root
    - include: roles/private.yml

    - include: roles/anyenv.yml
    - include: roles/ruby.yml
    - include: roles/node.yml
    - include: roles/erlang.yml
    - include: roles/elixir.yml
    # - include: roles/go.yml
    - include: roles/php.yml
    # - include: roles/swift.yml
    - include: roles/python.yml
      become: yes
      become_user: root
    # - include: roles/haskell.yml
    #   become: yes
    #   become_user: root
    - include: roles/neovim.yml
      become: yes
      become_user: root
    - include: roles/brightness-controller.yml
      become: yes
      become_user: root


