- name: install dependencies
  apt: name=software-properties-common state=present

- name: install repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'

- name: apt-get update
  apt:
    update_cache: yes

- name: install neovim
  apt: name=neovim state=present

- name: install python extension pip2
  pip:
    name: neovim
    executable: pip2
    extra_args: --user --upgrade

- name: install python extension pip3
  pip:
    name: neovim
    executable: pip3
    extra_args: --user --upgrade

