- name: install dependencies
  apt: name=software-properties-common state=present

- name: install repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'

- name: apt-get update
  apt:
    update_cache: yes

- name: install neovim
  apt: name=neovim state=present

- name: install python extension
  pip:
    name: neovim
    executable: {{ item }}
    extra_args: --user --upgrade
  with_items:
    - pip2
    - pip3

