- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common

- name: install repository
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: apt-get update
  apt:
    update_cache: yes

- name: install neovim
  apt: name={{ item }} state=present
  with_items:
    - neovim

- name: install python
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: install python extension
  pip:
    name: neovim
    executable: pip2
    extra_args: --user --upgrade

- name: install python extension
  pip:
    name: neovim
    executable: pip3
    extra_args: --user --upgrade
